apiVersion: v1
kind: Service
metadata:
  name: projet-web-service
spec:
  type: LoadBalancer  # Permet d'avoir une IP accessible (sur Docker Desktop -> localhost)
  selector:
    app: mon-projet-web # Doit correspondre au label du deployment
  ports:
    - protocol: TCP
      port: 80        # Port accessible depuis l'ext√©rieur (votre navigateur)
      targetPort: 5000 # Port interne du conteneur (celui du Flask)